export enum ActionTypeStates {
  INPROGRESS = "_INPROGRESS",
  SUCCESS = "_SUCCESS",
  FAIL = "_FAIL"
}

enum ActionTypeKeys {
  ADDTOBREADCRUMB_INSTORE = "ADDTOBREADCRUMB_INSTORE",
  GETUSER_SUCCESS = "GETUSER_SUCCESS",
  GETUSER_INPROGRESS = "GETUSER_INPROGRESS",
  GETUSER_FAIL = "GETUSER_FAIL"
}

export default ActionTypeKeys;
